service: serverless-telegram-bot
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  
plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    zip: true
    pythonBin: ${opt:pythonBin, self:provider.runtime}


package:
  patterns:
    - '*.py'
    - 'numpy'


functions:
  webhook:
    handler: handler.webhook
    events:
      - http: GET / 
